name: ahvn
channels:
    - conda-forge
    - defaults
dependencies:
    - python>=3.10,<3.14
    - pip
    - git
    # Core dependencies
    - pip:
        - apscheduler
        - babel
        - click
        - cloudpickle
        - dill
        - diskcache
        - docstring-parser
        - isodate
        - Jinja2
        - litellm
        - llama-index-core
        - openai
        - polib
        - prettytable
        - pydantic
        - pymongo
        - pyyaml
        - requests
        - sqlalchemy
        - sqlglot
        - termcolor
        - tenacity
        - -e .
